language: go

go:
  - "1.11.x"
  - "1.12.x"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get install -y libxml2-dev libxmlsec1-dev pkg-config
addons:
  apt:
    update: true


script:
  - make test
